In [2]:
import os
import re
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from concurrent.futures import ThreadPoolExecutor
from transformers import LlamaTokenizer, LlamaModel

ModuleNotFoundError: No module named 'torch'

In [12]:
# Map src directory
import sys
import os
root_dir = os.path.abspath(os.path.join(os.getcwd(), "../."))
print("Root Directory: ", root_dir)
src_dir = os.path.join(root_dir,"src")
print("Src Directory: ", src_dir)
sys.path.append(src_dir)
data_dir = os.path.join(root_dir,"data")
print("Data Directory: ", data_dir)

Root Directory:  /media/daniel/HDD1/AI894 - Capstone/Complete Collision Recorder
Src Directory:  /media/daniel/HDD1/AI894 - Capstone/Complete Collision Recorder/src
Data Directory:  /media/daniel/HDD1/AI894 - Capstone/Complete Collision Recorder/data

In [61]:
# Step 1: Load CSV Files
gcat_path = os.path.join(data_dir,"raw","gcat","20240924-2136-gcat-results.csv")
gcat_df = pd.read_csv(gcat_path)

/tmp/ipykernel_436619/896415136.py:3: DtypeWarning: Columns (50,54,61,62,64,68,70) have mixed types. Specify dtype option on import or set low_memory=False.
  gcat_df = pd.read_csv(gcat_path)

In [62]:
def pad_and_strip_variable(var):
    # Ensure the variable is a string and strip non-numeric characters
    var = re.sub(r'\D', '', str(var))
    
    # Pad with zeroes if the length is less than 12
    if len(var) < 12:
        padding_needed = 12 - len(var)
        var = var[:4] + '0' * padding_needed + var[4:]
    
    return var
gcat_df['CAD_ID'] = gcat_df['LOCAL_REPORT_NUMBER_ID'].apply(pad_and_strip_variable)

In [80]:
bikecle_labels_path = os.path.join(data_dir,"raw","bike_cle_narratives","callsforservice-quoted.csv")
bikecle_label_df = pd.read_csv(bikecle_labels_path)
bikecle_label_df.rename(columns={'event_number': 'CAD_ID'}, inplace=True)
bikecle_label_df['CAD_ID'] = bikecle_label_df['CAD_ID'].astype(str)

/tmp/ipykernel_436619/722184960.py:2: DtypeWarning: Columns (1,11,16,20,21,22,24,28,29,30,31,34,38,39,42,45,46,48,49,55,56,58,59,60) have mixed types. Specify dtype option on import or set low_memory=False.
  bikecle_label_df = pd.read_csv(bikecle_labels_path)

In [17]:
# Step 2: Read Text Files
def read_text_file(file_path):
    with open(file_path, 'r') as file:
        return file.read()

In [87]:
cad_text_dict = {}
oh1_text_dict = {}
cad_image_dir = os.path.join(data_dir, "processed", "cad_images")
oh1_image_dir = os.path.join(data_dir, "processed", "oh1_images")
def load_text_into_dict(image_dir,dir_name):
    with ThreadPoolExecutor() as executor:
        folder_paths = [os.path.join(image_dir, folder) for 
                        folder in os.listdir(image_dir) 
                        if os.path.isdir(os.path.join(image_dir, folder))]
        file_paths = []
        for folder in folder_paths:
            for file in os.listdir(folder):
                if file.endswith('.txt'):
                    file_paths.append(os.path.join(folder, file))
        results = executor.map(read_text_file, file_paths)
        for file_path, content in zip(file_paths, results):
            incident_id = os.path.basename(file_path).split('.')[0]
            dir_name[incident_id] = content

load_text_into_dict(cad_image_dir,cad_text_dict)
load_text_into_dict(oh1_image_dir,oh1_text_dict)

cad_text_df = pd.DataFrame(cad_text_dict.items(), columns=['CAD_ID', 'CAD_TEXT'])
def remove_extra_cad_chars(cad_id):
    return cad_id[:12]
cad_text_df['CAD_ID'] = cad_text_df['CAD_ID'].apply(remove_extra_cad_chars)

oh1_text_df = pd.DataFrame(oh1_text_dict.items(), columns=['CAD_ID', 'OH1_TEXT'])
def remove_extra_oh1_chars(cad_id):
    return "20" + cad_id[16:]
oh1_text_df['CAD_ID'] = oh1_text_df['CAD_ID'].apply(remove_extra_oh1_chars)

In [88]:
oh1_text_df.head()

         CAD_ID                                           OH1_TEXT
0  202100231011  MOTHER OF VICTIM STATED THAT HER 6 YEAR-OLD DA...
1  202000001607  WHILE UNIT1 WAS TURNING ONTO W44_, PEDESTRIAN ...
2  202000002644  (JNIT 1 IS S/B ON E.99 STREET TURNING E/B (LEF...
3  202000003892  E : UNIT #1 WAS DRIVING EASTBOUND ACROSS W117 ...
4  202000004207  OWNER OF UNIT #1 STATED SHE WAS OUTSIDE OF HER...

In [102]:
bikecle_label_df.head()

,primarykey,agency,CAD_ID,rev_num,call_datetime,call_type,call_desc,primary_unit,priority,call_source,...,call911_status,bluecam_status,wcs_status,oh1_status,countermeasures,victim,oshpoh1id,duplicate_of,is_motorcycle,ytids
0,8393467.0,CPD,202300352769,2.0,2023-11-22 11:17:55+00,INFW,INFO FOR A WARRANT PICK UP,NaN,4.0,ANI/ALI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8393469.0,CPD,202300352770,2.0,2023-11-22 11:20:46+00,TRUN,TROUBLE - UNKNOWN CAUSE,NaN,2.0,ANI/ALI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8393470.0,CPD,202300352771,2.0,2023-11-22 11:22:19+00,RFS,REC FILE SECTION EVENT- (RFS USE ONLY),NaN,5.0,Phone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8393471.0,CPD,202300352772,8.0,2023-11-22 11:22:33+00,CWEL,CHECK WELFARE OF A PERSON,2A37,2.0,ANI/ALI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8393472.0,CPD,202300352773,9.0,2023-11-22 11:22:51+00,SPOT,SHOTSPOTTER ALERT,4A34,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
from IPython.display import display, HTML

# Ensure all columns are displayed
pd.set_option('display.max_columns', None)

# Display the DataFrame in a scrollable div
display(HTML(gcat_df.head().to_html(classes='table table-striped table-hover', max_rows=5)))

In [113]:
bikecle_label_df[['CAD_ID','narrative']]

               CAD_ID narrative
0        202300352769       NaN
1        202300352770       NaN
2        202300352771       NaN
3        202300352772       NaN
4        202300352773       NaN
...               ...       ...
1709546  202300352764       NaN
1709547  202300352765       NaN
1709548  202300352766       NaN
1709549  202300352767       NaN
1709550  202300352768       NaN

[1709551 rows x 2 columns]

In [117]:
merged_text_df = pd.merge(cad_text_df, oh1_text_df, on='CAD_ID', how='outer', suffixes=('_cad', '_oh1'))

# Merge the result with bikecle_label_df on CAD_ID
merged_with_labels = pd.merge(merged_text_df, bikecle_label_df[['CAD_ID','narrative']], on='CAD_ID', how='left')

# Finally, merge the result with gcat_df on CAD_ID
final_merged_data = pd.merge(merged_with_labels, gcat_df[['CAD_ID','CRASH_SEVERITY_CD','U1_CONT_CIR_PRIMARY_CD','U1_PRECRASH_ACTION_CD','U1_TURN_CD','U1_TYPE_OF_UNIT_CD','U2_CONT_CIR_PRIMARY_CD','U2_PRECRASH_ACTION_CD','U2_TURN_CD','U2_TYPE_OF_UNIT_CD']], on='CAD_ID', how='left')

In [119]:
final_merged_data

,CAD_ID,CAD_TEXT,OH1_TEXT,narrative,CRASH_SEVERITY_CD,U1_CONT_CIR_PRIMARY_CD,U1_PRECRASH_ACTION_CD,U1_TURN_CD,U1_TYPE_OF_UNIT_CD,U2_CONT_CIR_PRIMARY_CD,U2_PRECRASH_ACTION_CD,U2_TURN_CD,U2_TYPE_OF_UNIT_CD
0,202000000930,INCIDENT REPORT PRINT DATE/TIME: 05/20/2024 10...,NaN,A driver struck an adult crossing an intersect...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,202000001607,NaN,"WHILE UNIT1 WAS TURNING ONTO W44_, PEDESTRIAN ...",A driver of a commercial truck turned left and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,202000002596,INCIDENT REPORT PRINT DATE/TIME: 05/20/2024 10...,NaN,A driver struck a person. The crash caused inj...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,202000002644,INCIDENT REPORT PRINT DATE/TIME: 05/20/2024 10...,(JNIT 1 IS S/B ON E.99 STREET TURNING E/B (LEF...,A driver turned left and struck and killed an ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,202000003457,INCIDENT REPORT PRINT DATE/TIME: 05/20/2024 10...,NaN,A driver struck an adult. The crash caused inj...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2169,202300386537,PRINT DATE/TIME: LOGIN ID: INCIDENT DATE/TIME:...,UNKNOWN EVENTS,A driver of an SUV turned left and struck an a...,4.0,2.0,6.0,LT,99.0,1.0,14.0,NT,23.0
2170,202300386861,INCIDENT REPORT PRINT DATE/TIME: 01/02/2024 10...,NaN,A driver of a transit bus struck a person.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2171,202300387472,PRINT DATE/TIME: 01/05/2024 06:37 LOGIN ID: GR...,NaN,A driver struck a person.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2172,202300388004,PRINT DATE/TIME: LOGIN ID: VECCHIOS INCIDENT: ...,NaN,A driver struck a person on a bicycle. The dri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2173,202400253534,INCIDENT REPORT PRINT DATE/TIME: 09/16/2024 13...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [122]:
from llama_models.llama3.api.datatypes import BuiltinTool

In [137]:
huggingface-cli login

SyntaxError: invalid syntax (1355118443.py, line 1)

In [136]:
cd /home/daniel/.llama/checkpoints/Llama3.1-8B
md5sum -c checklist.chk

SyntaxError: invalid decimal literal (155748573.py, line 1)

token = "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"

In [149]:
# Step 4: Preprocess Data
# tokenizer = LlamaTokenizer.from_pretrained('llama')
# model = LlamaModel.from_pretrained('llama')a
# https://www.llama.com/llama-downloads/
# Request ID: 1425674574766007

# Llama3.1-405B

from transformers import LlamaTokenizer, LlamaModel
import torch

# Replace <your_token> with your actual token
token = "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"


# Path to the local directory containing the tokenizer files
local_model_path = "/home/daniel/Documents/llama3.2-demo/llama-models/models"


# /home/daniel/Documents/llama3.2-demo
# tokenizer = LlamaTokenizer.from_pretrained("/home/daniel/Documents/llama3.2-demo/llama-models")
# model = LlamaModel.from_pretrained("/home/daniel/.llama/checkpoints/Llama3.1-8B")

# def preprocess(cad_text, oh1_text, indicator, label_text):
#     cad_tokens = tokenizer(cad_text, return_tensors='pt')
#     oh1_tokens = tokenizer(oh1_text, return_tensors='pt')
#     combined_tokens = {key: torch.cat([cad_tokens[key], oh1_tokens[key]], dim=1) for key in cad_tokens}

#     text_vector = model(**combined_tokens).last_hidden_state.mean(dim=1)
    
#     indicator_vector = torch.tensor(indicator.values, dtype=torch.float32)
#     label_tensor = torch.tensor(label_text.values, dtype=torch.long)
#     return text_vector, indicator_vector, label_tensor

# preprocessed_cad_data = [preprocess(text, indicator, label) for text, indicator, label in combined_data]

OSError: /home/daniel/Documents/llama3.2-demo/llama-models/models does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/daniel/Documents/llama3.2-demo/llama-models/models/main' for available files.